DROP TABLE IF EXISTS attendance_logs;
CREATE TABLE attendance_logs (
    id BIGINT PRIMARY KEY,
    "is_late" TEXT,
    "verify_status" TEXT,
    "sw_attendance_id" TEXT,
    "date" TEXT,
    "division_id" TEXT,
    "district_id" TEXT,
    "office_id" TEXT,
    "zone_id" TEXT,
    "area_id" TEXT,
    "meeting_point_id" TEXT,
    "shift_id" TEXT,
    "user_ids" TEXT,
    "location" TEXT,
    "checkout_type" TEXT,
    "submitted_by" TEXT,
    "created_at" TEXT,
    "updated_at" TEXT,
    "received_time" TEXT,
    "similarity_score" TEXT,
    "spoof_score" TEXT,
    "employee_type" TEXT,
    "employee_code" TEXT,
    "cnic" TEXT,
    "supervisor_name" TEXT,
    "supervisor_id" TEXT,
    "division_name" TEXT,
    "district_name" TEXT,
    "office_name" TEXT,
    "zone_name" TEXT,
    "area_name" TEXT,
    "shift_name" TEXT,
    "meeting_point_name" TEXT,
    "user_name" TEXT,
    "emp_designation_str" TEXT,
    "emp_designation_id" TEXT,
    "app_version" TEXT,
    "device" TEXT,
    "fake_attempt_count" TEXT,
    "liveness_count" TEXT,
    "mobile_approval_status" TEXT,
    "approved_by" TEXT,
    "users_user_ids_employee_type" TEXT,
    "users_user_ids_employee_typeemployee_type_wmc" TEXT,
    fetched_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_att_date ON attendance_logs(date);
